# Generated by Django 6.0 on 2026-02-25 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employerapp', '0002_employeedetails_delete_employerdetails'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employeedetails',
            old_name='empoyee_phone',
            new_name='employee_phone',
        ),
    ]
